Mission4/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4.Models
{
    // cretae the model with validation to ensure each input is between 0 and 100
    public class GradeCalculatorModel
    {
        [Range(0, 100)]
        public int Assignments { get; set; }
        [Range(0, 100)]
        public int GroupProjects { get; set; }
        [Range(0, 100)]
        public int Quizzes { get; set; }
        [Range(0, 100)]
        public int Midterm { get; set; }
        [Range(0, 100)]
        public int Final { get; set; }
        [Range(0, 100)]
        public int Intex { get; set; }
    }
}

Mission4/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission4/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    // Add an individual title to each page
    ViewData["Title"] = "Calculate Your Grade";
}

@model GradeCalculatorModel;

<h2>Grade Calculator</h2>
<p>Enter the percentage for each category</p>
<form method="post">
    <label>Assignments:</label>
    <input id="assignments" asp-for="Assignments"/><br />
    <label>Group Project:</label>
    <input id="groupProjects" asp-for="GroupProjects"/><br />
    <label>Quizzes:</label>
    <input id="quizzes" asp-for="Quizzes"/><br />
    <label>Midterm Exam:</label>
    <input id="midterm" asp-for="Midterm"/><br />
    <label>Final Exam:</label>
    <input id="final" asp-for="Final"/><br />
    <label>INTEX:</label>
    <input id="intex" asp-for="Intex"/><br /><br />
    <input id="submit" type="submit" value="Calculate Grade" />
    <!-- p tag containing the output of the grade calculation -->
    <p id="jsOutput"></p>
    <div asp-validation-summary="All"></div>
</form>
<br />


<!-- script tags for my js program, bootstrap, and jquery -->
<script src="js/Form.js"></script>

Mission4/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    // Add an individual title to each page
    ViewData["Title"] = "Mission 5 HomePage";
}




<!-- Header that lists your preferred name -->
<h1>Alli Pope</h1>
<br />


<!-- A picture of yourself doing something you enjoy -->
<img src="img/me.jpg" />
<br /><br />


<!-- A paragraph on what you hope to get out of this IS 413 class -->
<p>
    I'm simultaneously really excited and intimidated by this class.
    I have done quite a bit with Python and JavaScript in the IS core so far, but we have
    yet to touch a true  strongly-typed language. It's always been something I've been intimidated
    by, but I know it's a super important skill. So even though this class is well outside
    my comfort zone, I'm excited to grow as a programmer and learn a
    strongly-typed language for the first time.
</p>
<br />


<!-- A list of the Top #3 jobs you are most interested in pursuing when you graduate -->
<p>Jobs I'm most interested in:</p>
<ul>
    <li>Software Developer</li>
    <li>Data Analyst</li>
    <li>Security</li>
</ul>
<br />

Mission4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@*this is the shared layout for each of my pages. It includes all my links to css, bootstrap, jquery, and js*@
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <!-- A website title & An icon for the website -->
    <link rel="icon" href="img/smiley.png" />
    <title>@ViewData["Title"]</title>
    <!-- bootstrap and css sheets linked -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
</head>

<body>
    @*this is the header with navigation to the other pages*@
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>


    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/Form.js"></script>
</body>

</html>